services:
  postgres:
    image: postgres:15
    user: root
    restart: unless-stopped
    container_name: truco2-postgres
    environment:
      POSTGRES_PASSWORD: truco123
    volumes:
      - ./psql:/var/lib/postgresql/data
    networks:
      - appnet
    ports:
      - "5416:5432"

  pgadmin:
    image: dpage/pgadmin4
    user: root
    restart: unless-stopped
    container_name: truco2-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: truco2.user@ufam.com.br
      PGADMIN_DEFAULT_PASSWORD: truco123
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - appnet
    ports:
      - "16516:80"

networks:
  appnet:
    driver: bridge
