#CD GitHub Actions Workflow
name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /home/dev/truco2-db/
            git pull origin main
            DB_PORT="${{ vars.DB_PORT }}" DB_PASSWORD="${{ secrets.DB_PASSWORD }}" PGADMIN_PORT="${{ vars.PGADMIN_PORT }}" PGADMIN_PASSWORD="${{ secrets.PGADMIN_PASSWORD }}" docker compose up -d --build
